project_name: "MLops test"
author_name: "Kameshwari"
description: "Testing ML app"
author_email: "ksoundararajan@uabmc.edu"
repository_url: "https://anes-vstf.anesthesiology.uab.edu/tfs/DefaultCollection/Data%20Science/_git/TestExec"
data_dir: "data"
data_directory_name: "DATASCI"
mlflow_tracking_uri: "http://138.26.48.232:5000/"