project_name: "NotebookTemplate"
author_name: "Kameshwari"
description: "Jupyter Notebook Template"
author_email: "ksoundararajan@uabmc.edu"
repository_url: "https://anes-vstf.anesthesiology.uab.edu/tfs/DefaultCollection/Data%20Science/_git/NotebookTemplate"
data_dir: "data"
data_directory_name: "DATASCI"
llm_endpoint: "https://proxy-ai-anes-uabmc-awefchfueccrddhf.eastus2-01.azurewebsites.net/v1"
mlflow_tracking_uri: "http://138.26.48.232:5000/"
