# mkdocs.yml
site_name: {{project_name}}
site_url: https://sites.uab.edu/periop-datascience/
repo_url: https://github.com/uabperiopai
nav:
  - Home: index.md
  - '{{project_name}}':
    - Example Task A: '{{project_name}}/example_task_a.md'
    - Example Task B: '{{project_name}}/example_task_b.md'
  - '{{project_name}}_config':
    - Config: '{{project_name}}_Config/config.md'

  - llm_utils: '!include ./llm_utils/mkdocs.yml'

theme:
  name: readthedocs
plugins:
  - search
  - monorepo:
      submodules:
        - path: llm_utils
          repo_url: ''
  - mkdocstrings:
      handlers:
        python:
          paths: ['{{project_name}}', '{{project_name}}_config', user_interface, llm_utils]  # search packages in these folders
watch:
  - .  # reload docs for any file changes
use_directory_urls: false