# mkdocs.yml
site_name: '{{project_name}}'
site_url: https://sites.uab.edu/periop-datascience/
repo_url: https://github.com/uabperiopai
nav:
  - Home: index.md
  - 'User Interface': 'user_interface/{{project_name}}_app.md'
  - '{{project_name}}':
    - streamlit_interface: '{{project_name}}/streamlit_interface.md'
    - 'Utils':
      - 'utils_example': '{{project_name}}/utils/utils_example.md'
  - '{{project_name}}_config':
    - Config: '{{project_name}}_config/config.md'

  - llm_utils: '!include ./llm_utils/mkdocs.yml'

theme:
  name: readthedocs
plugins:
  - search
  - monorepo:
      submodules:
        - path: llm_utils
          repo_url: ''
  - mkdocstrings:
      handlers:
        python:
          paths: ['{{project_name}}', '{{project_name}}_config', user_interface, llm_utils]  # search packages in these folders
watch:
  - .  # reload docs for any file changes
use_directory_urls: false